import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import CampaignCard from '../components/CampaignCard'
import { dataService } from '../services/dataService'

export default function Home(){const [items,setItems]=useState([]),[q,setQ]=useState('');const nav=useNavigate();useEffect(()=>{dataService.listCampaigns().then(setItems)},[]);return <main>
<section className="hero"><div className="shell heroGrid"><div><span className="eyebrow">♥ AJUDE • PARTICIPE • COMPARTILHE</span><h1>Uma ajuda que pode <em>virar prêmio.</em></h1><p>Descubra campanhas, escolha seus números e acompanhe suas participações. Ou crie sua própria Ajuda Premiada.</p><form className="search" onSubmit={e=>{e.preventDefault();nav(`/explorar?q=${encodeURIComponent(q)}`)}}><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Busque campanha, causa, prêmio ou cidade"/><button>Buscar</button></form><div className="trust"><span>✓ Regras visíveis</span><span>✓ Participação simples</span><span>✓ Busca por cidade e causa</span></div></div><div className="heroArt"><div className="orbit"/><div className="gift">🎁<b>Ajuda Premiada</b><small>Ajude uma causa. Participe.</small></div><div className="float one">♥ <b>+1 ajuda</b><small>uma causa ganhou força</small></div><div className="float two">★ <b>Número escolhido</b><small>participação registrada</small></div></div></div></section>
<section className="stats"><div><b>{items.length}+</b><span>campanhas disponíveis</span></div><div><b>100%</b><span>regras visíveis</span></div><div><b>Pix</b><span>direto ao organizador</span></div><div><b>Brasil</b><span>busca por cidade e causa</span></div></section>
<section className="shell section"><div className="heading"><div><span className="eyebrow">EM DESTAQUE</span><h2>Escolha uma causa para apoiar</h2></div><Link to="/explorar">Ver todas →</Link></div><div className="grid">{items.slice(0,4).map(c=><CampaignCard key={c.id} campaign={c}/>)}</div></section>
<section className="soft section"><div className="shell"><div className="center"><span className="eyebrow">COMO FUNCIONA</span><h2>Simples para ajudar. Completo para organizar.</h2></div><div className="steps"><article><b>01</b><span>🔎</span><h3>Encontre</h3><p>Busque por causa, tema, cidade ou prêmio.</p></article><article><b>02</b><span>🔢</span><h3>Escolha</h3><p>Selecione números disponíveis e confira as regras.</p></article><article><b>03</b><span>◇</span><h3>Ajude via Pix</h3><p>O valor é direcionado ao Pix informado pelo organizador.</p></article><article><b>04</b><span>🏆</span><h3>Acompanhe</h3><p>Veja participações, números e informações da campanha.</p></article></div></div></section>
<section className="shell cta"><div><span className="eyebrow">PARA ORGANIZADORES</span><h2>Tem uma causa ou projeto que precisa de apoio?</h2><p>Defina prêmios, quantidade e valor dos números, Pix, cidade, sorteio e textos personalizados.</p><Link className="btn primary big" to="/criar">Criar minha Ajuda Premiada</Link></div><div className="ctaIcon">🎯</div></section>
</main>}
